# Generated by Django 2.2.2 on 2019-06-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
