# Generated by Django 2.2.2 on 2019-06-05 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blog_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='Глянули', to=settings.AUTH_USER_MODEL),
        ),
    ]
